name: 'ecommerce_dashboard_project'
version: '1.0.0'
config-version: 2

profile: 'ecommerce_dashboard_project'

model-paths: ["models/ecommerce_dashboard_project"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  ecommerce_dashboard_project:
    +materialized: view
    staging:
      +materialized: view
    marts:
      +materialized: view
      core:
        +materialized: view
